var json_GroundTruthDesember_8 = {
  type: "FeatureCollection",
  name: "GroundTruthDesember_8",
  crs: { type: "name", properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  features: [
    {
      type: "Feature",
      properties: {
        fid: "1",
        Nama: "Lokasi 1",
        Lattitude: -6.153,
        Longitude: 107.4493,
        Waktu: "06:48:05",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "Vegetatif Akhir",
        Photo: "Lokasi 1.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.4493, -6.153] },
    },
    {
      type: "Feature",
      properties: {
        fid: "2",
        Nama: "Lokasi 2",
        Lattitude: -6.153,
        Longitude: 107.4489,
        Waktu: "07:34:24",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "Generatif",
        Photo: "Lokasi 2.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.4489, -6.153] },
    },
    {
      type: "Feature",
      properties: {
        fid: "3",
        Nama: "Lokasi 3",
        Lattitude: -6.1519,
        Longitude: 107.4481,
        Waktu: "07:50:24",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "-",
        Photo: "Lokasi 3.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.4481, -6.1519] },
    },
    {
      type: "Feature",
      properties: {
        fid: "4",
        Nama: "Lokasi 4",
        Lattitude: -6.1487,
        Longitude: 107.4452,
        Waktu: "07:53:06",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "Generatif",
        Photo: "Lokasi 4.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.4452, -6.1487] },
    },
    {
      type: "Feature",
      properties: {
        fid: "5",
        Nama: "Lokasi 5",
        Lattitude: -6.1485,
        Longitude: 107.445,
        Waktu: "07:54:21",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "Generatif",
        Photo: "Lokasi 5.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.445, -6.1485] },
    },
    {
      type: "Feature",
      properties: {
        fid: "6",
        Nama: "Lokasi 6",
        Lattitude: -6.16325,
        Longitude: 107.44308,
        Waktu: "08:00:32",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "Panen",
        Photo: "Lokasi 6.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.443083, -6.16325] },
    },
    {
      type: "Feature",
      properties: {
        fid: "7",
        Nama: "Lokasi 7",
        Lattitude: -6.1634,
        Longitude: 107.4429,
        Waktu: "08:00:36",
        Tanggal: "28 Desember 2025",
        Lokasi: "Sumberjaya, Kec Tempuran, Karawang Jawa Barat",
        "Fase Ground Check": "Panen",
        Photo: "Lokasi 7.jpeg",
      },
      geometry: { type: "Point", coordinates: [107.4429, -6.1634] },
    },
  ],
};
